name: scandit_flutter_datacapture_core
description: This plugin builds the foundation of all data capture related functionality offered by the Scandit Data Capture SDK.
version: 6.24.0
homepage: https://scandit.com

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  linter: ^1.30.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.core
        pluginClass: ScanditFlutterDataCaptureCorePlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureCore
