name: scandit_flutter_datacapture_core
description: Scandit Data Capture SDK for Flutter. ScanditCaptureCore builds the foundation of all data capture related functionality offered by the Scandit Data Capture SDK. It contains classes and interfaces shared between the data capture modules.
version: 6.17.1
homepage: https://scandit.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  linter: ^1.30.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.core
        pluginClass: ScanditFlutterDataCaptureCorePlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureCorePlugin
