name: scandit_flutter_datacapture_core
description: This plugin builds the foundation of all data capture related functionality offered by the Scandit Data Capture SDK.
version: 7.2.4
homepage: https://scandit.com

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.core
        pluginClass: ScanditFlutterDataCaptureCorePlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureCore
